---
- hosts: all
  vars:
    contries: ["India","Lanka","New york","US"]
    students:
      - name: yaman
        id: 5
      - name: Rohan
        id: 2
    pkgs:
     name: httpd
     vendor: apache
     version: 7 
    
  tasks:
    - name: loop over contries and students
      debug:
        msg: "{{item}}"
      loop: "{{contries}}"
    - name: loop over students
      debug:
        msg: "Student name is : {{item.name}}, roll no is: {{item.id}}"
      loop: "{{students}}"
    - name: loop over dictionary
      debug:
        msg: "{{item}}"
      loop: "{{pkgs | dict2items}}"
      ## Loop requires list, in order to convert dict to list, we convert dictionary to list

    - name: loop over range of 10
      debug:
        msg: "Count is : {{item}}"
      loop: "{{range(10) | list}}"

    - name: loop over range of even numbers
      debug:
        msg: "Count is : {{item}}"
      loop: "{{range(0,11,2) | list}}"

    - name: loop over range of even numbers when item divisible by 2
      debug:
        msg: "Count is : {{item}}"
      loop: "{{range(1,20) | list}}"
      when: item%2 == 0